pom.xml
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> CAMEL-14840 - fix weld3 version

examples/camel-example-spring-boot-undertow-spring-security/pom.xml, examples/camel-example-spring-boot-undertow-spring-security/readme.adoc, examples/camel-example-spring-boot-undertow-spring-security/realm-export.json, examples/camel-example-spring-boot-undertow-spring-security/src/main/java/org/apache/camel/example/undertow/spring/boot/Application.java, examples/camel-example-spring-boot-undertow-spring-security/src/main/java/org/apache/camel/example/undertow/spring/boot/SecurityConfiguration.java, examples/camel-example-spring-boot-undertow-spring-security/src/main/resources/application.properties, examples/pom.xml
Issue: https://issues.apache.org/jira/browse/CAMEL-15007
Example of the usage of the camel-undertow-spring-security component with the Keycloak server.
=> CAMEL-15007 camel-undertow-spring-security create example of usage

core/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/CamelMainRunController.java, core/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/CamelSpringBootApplicationController.java, core/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/CamelSpringBootApplicationListener.java
NOTE requires https://github.com/apache/camel/pull/3820 to be merged on master
=> CAMEL-15056: camel-main: provide a way to bring a custom engine to control shutdown logic

components-starter/camel-opentelemetry-starter/src/main/docs/opentelemetry-starter.adoc, components-starter/camel-opentelemetry-starter/src/main/java/org/apache/camel/opentelemetry/starter/CamelOpenTelemetry.java, components-starter/camel-opentelemetry-starter/src/main/java/org/apache/camel/opentelemetry/starter/OpenTelemetryAutoConfiguration.java, components-starter/camel-opentelemetry-starter/src/main/java/org/apache/camel/opentelemetry/starter/OpenTelemetryConditionalAutoConfiguration.java, components-starter/camel-opentelemetry-starter/src/main/java/org/apache/camel/opentelemetry/starter/OpenTelemetryConfigurationProperties.java, components-starter/camel-opentelemetry-starter/src/main/resources/META-INF/spring.factories
Signed-off-by: Ruben <ruben.vp8510@gmail.com>
Still require some work, but if someone can start to review please? 
Thanks.
=> Opentelemetry spring boot support

docs/modules/ROOT/pages/spring-cloud-netflix.adoc
Changes from "balabncer" to "balancer"
=> Document update

components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/EncryptedPropertiesCustomConfigurationBeansTest.java
fix test case failing in windows
=> CAMEL-15649 : Fixing test case error by NativePRNG SecureRandom not available in Windows

catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/others.properties, catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/others/leveldb-legacy.json, components-starter/README.adoc, components-starter/camel-leveldb-legacy-starter/pom.xml, components-starter/camel-leveldb-legacy-starter/src/main/resources/META-INF/LICENSE.txt, components-starter/camel-leveldb-legacy-starter/src/main/resources/META-INF/NOTICE.txt, components-starter/camel-leveldb-legacy-starter/src/main/resources/META-INF/spring.provides, components-starter/pom.xml, docs/modules/ROOT/pages/list.adoc, tooling/camel-spring-boot-bom/pom.xml, tooling/camel-spring-boot-dependencies/pom.xml
fixes https://issues.apache.org/jira/browse/CAMEL-15735
=> https://issues.apache.org/jira/browse/CAMEL-15735

components-starter/camel-undertow-spring-security-starter/src/main/java/org/apache/camel/undertow/spring/boot/UndertowSpringSecurityCustomizer.java
fixes https://issues.apache.org/jira/browse/CAMEL-15750
I refactored undertow-spring-security starter to use `ComponentCustomizer`. Problem reported by the issue is solved, because now it sets correctly `securityConfiguration` into `UndertowComponent`.
=> CAMEL-15750 camel-undertow-spring-security-starter always forbidden

archetypes/camel-archetype-spring-boot/src/main/resources-filtered/META-INF/maven/archetype-metadata.xml, archetypes/camel-archetype-spring-boot/src/main/resources/archetype-resources/readme.adoc
=> Add readme.adoc to archetype metadata and remove camelroutes actuator call info

catalog/camel-catalog-provider-springboot/src/main/java/org/apache/camel/springboot/catalog/SpringBootRuntimeProvider.java
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Factorize code in SpringBootRuntimeProvider

core/camel-spring-boot/src/main/docs/spring-boot.adoc, core/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/cloud/CamelCloudConfigurationProperties.java, core/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/cloud/CamelCloudServiceDiscoveryAutoConfiguration.java, core/camel-spring-boot/src/test/java/org/apache/camel/spring/boot/cloud/CamelCloudServiceCallConfigurationTest.java
=> CAMEL-16448: Added configuration for service definitions with metadata

docs/README_local_build.adoc, docs/local-build.sh, docs/source-map.yml, docs/source-watch.yml
Sets up new docs local-build for camel-spring-boot main. See apache/camel-website#731
=> update to docs local build v2

docs/README_local_build.adoc, docs/local-build.sh, docs/source-map.yml, docs/source-watch.yml
Sets up new docs local-build for camel-spring-boot 3.14.x. See apache/camel-website#731
=> Camel spring boot 3.14.x local build v2

tooling/camel-spring-boot-dependencies-generator/pom.xml
This should fix the build error caused by the dep changes on Camel Core
=> CAMEL-17435 fix

components-starter/camel-springdoc-starter/src/main/java/org/apache/camel/springboot/springdoc/SpringdocAutoConfiguration.java
https://issues.apache.org/jira/browse/CAMEL-17548
=> CAMEL-17548: camel-springdoc-starter - Fix to check apiProperties

tests/camel-spring-boot-integration-tests/infinispan/pom.xml, tests/camel-spring-boot-integration-tests/infinispan/src/main/java/org/apache/camel/integration/springboot/infinispan/InfinispanRoutes.java, tests/camel-spring-boot-integration-tests/infinispan/src/test/java/org/apache/camel/integration/springboot/infinispan/InfinispanTest.java, tests/camel-spring-boot-integration-tests/integration-common/pom.xml, tests/camel-spring-boot-integration-tests/integration-common/src/main/java/org/apache/camel/integration/springboot/Application.java, tests/camel-spring-boot-integration-tests/integration-common/src/main/java/org/apache/camel/integration/springboot/SpringBootBaseIntegration.java, tests/camel-spring-boot-integration-tests/pom.xml
POC for integration test on C3SB
=> ✅ Add integration test module + infinispan

components-starter/camel-fhir-starter/pom.xml, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/AbstractFhirTestSupport.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/CustomFhirConfiguration.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/CustomNoFhirServerUrlCamelContext.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/DefaultCamelContext.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirCapabilitiesTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirConfigurationTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirCreateTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirCustomClientConfigurationTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirDeleteTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirExtraParametersTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirHistoryTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirLoadPageTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirMetaTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirOperationTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirPatchTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirReadTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirSearchTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirServer.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirSimpleTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirTransactionTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirUpdateTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirValidateTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/Hl7v2PatientToFhirPatientTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/PatientProcessor.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/dataformat/FhirJsonDataFormatTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/dataformat/FhirJsonDataformatErrorHandlerTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/dataformat/FhirXmlDataFormatTest.java, components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/dataformat/FhirXmlDataformatErrorHandlerTest.java
https://issues.apache.org/jira/browse/CAMEL-17725
Thanks !
=> [CAMEL-17725] Add tests in camel-fhir-starter

README.md
=> Add a friendly link to the Spring Boot section of the Camel website

components-starter/camel-slack-starter/pom.xml, components-starter/camel-slack-starter/src/test/java/org/apache/camel/component/slack/springboot/SlackComponentVerifierExtensionTest.java, components-starter/camel-slack-starter/src/test/java/org/apache/camel/component/slack/springboot/SlackProducerTest.java
(cherry picked from commit a680db972ef603429da5edb6e26c008eb26e1733)
=> [CAMEL-17766]add tests in camel-slack-starter

components-starter/camel-webhook-starter/pom.xml, components-starter/camel-webhook-starter/src/test/java/org/apache/camel/component/webhook/springboot/TestComponent.java, components-starter/camel-webhook-starter/src/test/java/org/apache/camel/component/webhook/springboot/TestEndpoint.java, components-starter/camel-webhook-starter/src/test/java/org/apache/camel/component/webhook/springboot/WebhookBasePathTest.java, components-starter/camel-webhook-starter/src/test/java/org/apache/camel/component/webhook/springboot/WebhookHttpBindingTest.java, components-starter/camel-webhook-starter/src/test/java/org/apache/camel/component/webhook/springboot/WebhookMultiRouteTest.java, components-starter/camel-webhook-starter/src/test/java/org/apache/camel/component/webhook/springboot/WebhookPathTest.java, components-starter/camel-webhook-starter/src/test/java/org/apache/camel/component/webhook/springboot/WebhookUriEncodingTest.java
(cherry picked from commit e79c618cbb3e109308c4f3f990a951d942f95fb6)
=> [CAMEL-17777]add tests in camel-webhook-starter

components-starter/camel-aws2-ddb-starter/pom.xml, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/BaseDdb2.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddb/Ddb2BatchGetItemsTest.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddb/Ddb2DeleteItemTest.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddb/Ddb2DeleteTableTest.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddb/Ddb2DescribeTableRuleIT.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddb/Ddb2GetItemTest.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddb/Ddb2QueryTest.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddb/Ddb2ScanTest.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddb/Ddb2UpdateItemTest.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddb/Ddb2UpdateTableByIdTest.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddbstream/Ddb2StreamTest.java
Issue: https://issues.apache.org/jira/browse/CAMEL-17846
Added tests for all supported operation of aws2-ddb-producer (see [documentation](https://camel.apache.org/components/3.15.x/aws2-ddb-component.html#_supported_producer_operationshttps://camel.apache.org/components/3.15.x/aws2-ddb-component.html#_supported_producer_operations))
Added basic test to cover ddbastreams.
=> CAMEL-17846 add tests in camel-aws2-ddb-starter

components-starter/camel-master-starter/pom.xml, components-starter/camel-master-starter/src/test/java/org/apache/camel/component/master/springboot/EndpointUriEncodingTest.java, components-starter/camel-master-starter/src/test/java/org/apache/camel/component/master/springboot/MasterComponentTest.java, components-starter/camel-master-starter/src/test/resources/log4j2.properties
Tests for camel-master-starter (ported the tests from camel-master).
https://issues.apache.org/jira/browse/CAMEL-17900
Thanks!
=> [CAMEL-17900] - add tests in camel-master-starter.

core/camel-spring-boot/src/main/docs/spring-boot.adoc, core/camel-spring-boot/src/main/docs/starter-configuration.adoc, docs/spring-boot/modules/ROOT/nav.adoc, docs/spring-boot/modules/ROOT/pages/index.adoc
https://issues.apache.org/jira/browse/CAMEL-17933
Thanks !
=> [CAMEL-17933] Add documentation on configuring camel starters

components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/BaseDdb2.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddb/Ddb2QueryTest.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddb/Ddb2ScanTest.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddb/Ddb2UpdateItemTest.java, components-starter/camel-aws2-ddb-starter/src/test/java/org/apache/camel/component/aws2/ddb/Ddb2UpdateTableByIdTest.java, components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/BaseSqs.java, components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/JmsStyleSelectorTest.java, components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/SqsComponentTest.java, components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/SqsDeadletterTest.java, components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/SqsOperationsTest.java, components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/SqsProducerAutoCreateQueueTest.java
camel-aws2-ddb-starter and camel-aws2-sqs-starter using wrong Configuration class import
=> Use org.springframework.context.annotation.Configuration for Annotation

components-starter/camel-aws2-s3-starter/pom.xml, components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/BaseS3.java, components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3BatchConsumerTest.java, components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3ComponentTest.java, components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3CopyObjectCustomerKeyTest.java, components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3CopyObjectOperationTest.java, components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3CreateDownloadLinkOperationTest.java, components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3ListObjectsOperationTest.java, components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3MoveAfterReadConsumerTest.java, components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3MultipartUploadOperationTest.java, components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3ObjectRangeOperationTest.java, components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3PojoAsBodyTest.java, components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3SimpleEncryptedUploadOperationTest.java, components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3StreamUploadOperationTest.java
Issue: https://issues.apache.org/jira/browse/CAMEL-17920
=> CAMEL-17920 add tests in camel-aws2-s3-starter

components-starter/camel-kafka-starter/src/main/java/org/apache/camel/component/kafka/springboot/KafkaComponentConfiguration.java, components-starter/camel-kafka-starter/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java
Respond to changes in SeekPolicy API here https://github.com/apache/camel/commit/2de2764a687ae59d8b035a2163b269ab88850a1b
=> CAMEL-17051 Respond to SeekPolicy changes in camel

components-starter/camel-file-starter/pom.xml, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/AntPathMatcherGenericFileFilterTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/BaseFile.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileBeginFailureOneTimeTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileBridgeErrorHandlerTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileBrowsableEndpointTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileChangedReadLockMarkerFileFalseTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileConsumerAbsolutePathDefaultMoveTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileConsumerBatchTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileConsumerFileExpressionTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileConsumerFileFilterTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileConsumerIdempotentTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileConsumerMoveAndMoveFailureTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileConsumerPreMoveTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileIdempotentReadLockWithFileIdempRepoTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileIdempotentReadSameFileAgainTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileProduceTempPrefixTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileProducerCharsetUTFtoISOTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileProducerExpressionTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileProducerFileExistOverrideTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileProducerOverruleToDifferentFolderTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileProducerRecursivelayToDifferentFolderTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileProducerStreamTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileSorterRefTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FileToFileWithFlattenTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FilerConsumerDoneFileNamePrefixTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FilerProducerDoneFileNameRouteTest.java, components-starter/camel-file-starter/src/test/java/org/apache/camel/component/file/FromFileMoveFileIfProcessFailsTest.java
Issue: https://issues.apache.org/jira/browse/CAMEL-17959
=> CAMEL-17959 Add tests in camel-file-starter

components-starter/camel-aws2-kinesis-starter/pom.xml, components-starter/camel-aws2-kinesis-starter/src/test/java/org/apache/camel/component/aws2/kinesis/BaseKinesis.java, components-starter/camel-aws2-kinesis-starter/src/test/java/org/apache/camel/component/aws2/kinesis/KinesisComponentTest.java
Issue: https://issues.apache.org/jira/browse/CAMEL-17982
=> CAMEL-17982 Add tests in camel-aws2-kinesis

components-starter/camel-sql-starter/pom.xml, components-starter/camel-sql-starter/src/test/java/org/apache/camel/component/sql/BaseSql.java
seems like that H2 is more reliable compared to derby, with H2 tests are not flaky anymore
=> Fix SQL flaky test

tooling/camel-spring-boot-bom/pom.xml, tooling/camel-spring-boot-dependencies/pom.xml, tooling/camel-spring-boot-generator-maven-plugin/src/main/java/org/apache/camel/springboot/maven/BomGeneratorMojo.java
Add missing camel-spring-boot artifacts to the camel-spring-boot BOM
=> chore : add missing artifacts to the bom, refresh JSON

components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/PlatformHttpTest.java
fixes https://issues.apache.org/jira/browse/CAMEL-18071
Reflects change of https://github.com/apache/camel/commit/638aadf20e2ab76deb91a2fc561e0ffdd5104d5e#diff-595aa229dc464404fcc8a52ba4d79bee55eb25af224a02099d7b044edc771833L125
=> CAMEL-18071 Camel-http-platform-starter compilation problem in test module

.github/dependabot.yml
=> (chores) ci: keep GH actions up-to-date

.github/workflows/depsreview.yaml
=> (chores) ci: included dependency review

pom.xml
https://github.com/apache/camel/pull/8026
=> ⬆️ [CAMEL-18294] upgrade to spring boot 2.7.2

pom.xml
Cherry pick from main->camel-spring-boot-3.18.x LTS branch
=> Align to spring boot 2.7.3 (#608)

archetypes/camel-archetype-spring-boot/pom.xml, pom.xml
https://issues.apache.org/jira/browse/CAMEL-18409
=> Upgrade to spring boot 2.6.11

components-starter/camel-paho-starter/src/test/java/org/apache/camel/component/paho/springboot/PahoComponentTest.java, components-starter/camel-paho-starter/src/test/java/org/apache/camel/component/paho/springboot/PahoOverrideTopicTest.java, components-starter/camel-paho-starter/src/test/java/org/apache/camel/component/paho/springboot/PahoToDSendDynamicTest.java, components-starter/camel-paho-starter/src/test/java/org/apache/camel/component/paho/springboot/PahoToDTest.java
Bring over changes from https://github.com/apache/camel/commit/05b177868f63e111abaa0fce39ea68fd22a8ee49 to camel-spring-boot tests; add a cleanUp method.
=> Adjust test lifecycle to recent refactoring in camel-test-infra-activemq

components-starter/camel-kamelet-starter/src/test/java/org/apache/camel/component/kamelet/springboot/KameletGlobalPropertiesTest.java
Apply fixes from https://github.com/apache/camel/commit/dd4371a81d9c14d08421a6aa62bcdb6b1f4ae986 to camel-spring-boot's version of KameletGlobalPropertiesTest.java
=> Apply fixes from CAMEL-18370 to camel-spring-boot

components-starter/camel-cxf-soap-starter/pom.xml
=> ➖ Add  scope test to test-jar type

components-starter/camel-servlet-starter/src/test/java/org/apache/camel/component/servlet/springboot/test/ServletAttachmentMultiPartTest.java
=> ✅  Add Servlet Attachment test

components-starter/camel-telegram-starter/src/test/java/org/apache/camel/component/telegram/springboot/TelegramConsumerHealthCheckErrorTest.java
Apply fixes to tests in camel (https://github.com/apache/camel/commit/161b5c84601c115f8297c7cc652da8a326aa50a9)
=> Apply fixes from CAMEL-18506

tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelServletTest.java, tooling/camel-spring-boot-bom/pom.xml, tooling/camel-spring-boot-dependencies-generator/pom.xml, tooling/camel-spring-boot-dependencies/pom.xml, tooling/camel-spring-boot-generator-maven-plugin/src/main/java/org/apache/camel/springboot/maven/BomGeneratorMojo.java
I was wondering if https://github.com/apache/camel-spring-boot/compare/main...Croway:cleanup-boms?expand=1#diff-6b74b1847f48b03edc897908eb7ae2c657e81124830cd07bfb77ea9ac58ad036L1718 should be removed too
=> BOMs cleanup

components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3CreateDownloadLinkOperationTest.java
cherry pick from https://github.com/apache/camel-spring-boot/pull/760
=> Make S3CreateDownloadLinkOperationTest FIPS compliant

pom.xml, tooling/camel-spring-boot-dependencies-generator/pom.xml
Fix for https://issues.apache.org/jira/browse/CAMEL-18920
In order to get the latest improvements and bug fixes, we need to upgrade to Groovy 4.
* Change the version of Groovy to `4.0.9`
* Change group id to `org.apache.groovy`
=> CAMEL-18920: Upgrade to Groovy 4.x

catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/others.properties, catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/others/observation.json, components-starter/camel-observation-starter/pom.xml, components-starter/camel-observation-starter/src/main/docs/observation.json, components-starter/camel-observation-starter/src/main/java/org/apache/camel/observation/starter/CamelObservation.java, components-starter/camel-observation-starter/src/main/java/org/apache/camel/observation/starter/ObservationAutoConfiguration.java, components-starter/camel-observation-starter/src/main/java/org/apache/camel/observation/starter/ObservationConditionalAutoConfiguration.java, components-starter/camel-observation-starter/src/main/java/org/apache/camel/observation/starter/ObservationConfigurationProperties.java, components-starter/camel-observation-starter/src/main/resources/META-INF/LICENSE.txt, components-starter/camel-observation-starter/src/main/resources/META-INF/NOTICE.txt, components-starter/camel-observation-starter/src/main/resources/META-INF/spring.provides, components-starter/camel-observation-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, components-starter/pom.xml, tooling/camel-spring-boot-bom/pom.xml, tooling/camel-spring-boot-dependencies/pom.xml
fixes https://issues.apache.org/jira/browse/CAMEL-19209
=> Added support for Micrometer Observation

components-starter/camel-infinispan-starter/pom.xml, components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/NewIssuesConsumerTest.java, components-starter/camel-mongodb-starter/pom.xml
Some tests are failing during PR jobs, I'll try to fix them with this PR
=> Fix failing tests

pom.xml
Upgrade spring-boot version to 2.7.14
=> Upgrade spring-boot to 2.7.14

components-starter/camel-consul-starter/src/main/java/org/apache/camel/component/consul/springboot/cluster/ConsulClusterServiceAutoConfiguration.java, components-starter/camel-infinispan-starter/src/main/docs/infinispan.json, components-starter/camel-infinispan-starter/src/main/java/org/apache/camel/component/infinispan/remote/springboot/cluster/InfinispanRemoteClusterServiceAutoConfiguration.java, components-starter/camel-infinispan-starter/src/main/java/org/apache/camel/component/infinispan/remote/springboot/cluster/InfinispanRemoteClusterServiceConfiguration.java, components-starter/camel-infinispan-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, components-starter/camel-jgroups-raft-starter/src/main/java/org/apache/camel/component/jgroups/raft/springboot/cluster/springboot/JGroupsRaftClusterServiceAutoConfiguration.java, components-starter/camel-jgroups-starter/src/main/java/org/apache/camel/component/jgroups/springboot/cluster/springboot/JGroupsLockClusterServiceAutoConfiguration.java, components-starter/camel-kubernetes-starter/src/main/java/org/apache/camel/component/kubernetes/springboot/cluster/KubernetesClusterServiceAutoConfiguration.java, components-starter/camel-zookeeper-starter/src/main/java/org/apache/camel/component/zookeeper/springboot/cluster/ZooKeeperClusterServiceAutoConfiguration.java
fixes https://issues.apache.org/jira/browse/CAMEL-19829
=> Refactor cluster service autoconfiguration

components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirUpdateIT.java
The test was failing on the CI, the upgrade should fix it
=> Upgrade failing test to FHIR 6.6.1

jenkins.ppc64le
Hi @oscerd added jenkinsfile for power support. Thanks.
=> Camel-Spring-Boot: Adding jenkinsfile for ppc64le

pom.xml
=> Upgrade to spring-boot 3.1.5

tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/util/DependencyResolver.java
Set features to DocumentBuilderFactory to protect from XXE; fix for SAST
=> Set features to DocumentBuilderFactory to protect from XXE; fix for SAST

components-starter/camel-zipfile-starter/src/test/java/org/apache/camel/dataformat/zipfile/springboot/ZipFileDataFormatTest.java
Add a check for path traversal for SAST tests
=> Add a check for path traversal for SAST tests

components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbFindOperationIT.java
MongoDB was updated in the test infra, and the version override is not needed anymore
=> Remove custom mongodb version

components-starter/camel-spring-jdbc-starter/pom.xml
https://issues.apache.org/jira/browse/CAMEL-20238
Thanks !
=> CAMEL-20238: camel-jdbc-starter - add spring-boot-starter-jdbc

Jenkinsfile.sb.ppc64le.jdk11.ppc64le
Hi @oscerd to enable JDK11 jobs for power for camel-spring-boot 3.x
=> Adding Jenkins file for PPC64LE JDK11

components-starter/camel-http-starter/pom.xml
`mvnd` complains about duplicated dependencies in the same pom.xml
=> Remove duplicate dependency

core/camel-spring-boot/pom.xml, core/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/actuate/health/CamelAvailabilityCheckAutoConfiguration.java
Since spring-boot-actuator causes failures on jkube deployments
=> Removes SB actuator compile dependency

components-starter/camel-jasypt-starter/src/main/java/org/apache/camel/component/jasypt/springboot/JasyptEncryptedPropertiesAutoconfiguration.java, components-starter/camel-jasypt-starter/src/main/java/org/apache/camel/component/jasypt/springboot/JasyptSpringEncryptedPropertiesParser.java
Make Jasypt beans conditional so that can be overridden
=> cherry-pick CAMEL-20738 Make Jasypt beans conditional so that can be overridden

pom.xml, tooling/camel-spring-boot-dependencies/pom.xml
Update spring-boot version to 3.2.8
=> Update to spring-boot 3.2.8

components-starter/camel-jolokia-starter/pom.xml, components-starter/camel-jolokia-starter/src/main/docs/.gitignore, components-starter/camel-jolokia-starter/src/main/docs/jolokia.adoc, components-starter/camel-jolokia-starter/src/main/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfiguration.java, components-starter/camel-jolokia-starter/src/main/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentConfiguration.java, components-starter/camel-jolokia-starter/src/main/java/org/apache/camel/component/jolokia/springboot/restrictor/CamelRestrictor.java, components-starter/camel-jolokia-starter/src/main/resources/META-INF/LICENSE.txt, components-starter/camel-jolokia-starter/src/main/resources/META-INF/NOTICE.txt, components-starter/camel-jolokia-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationCustomRestrictorTest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationDefaultRestrictorTest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationDisabledTest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationOnK8SDisabledTest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationOnK8STest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationPrefersBeanTest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationPrefersPropertiesTest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationTest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationUsingConfigHolderTest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationUsingCustomBeansTest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationUsingSystemPropertiesTest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationWithoutRestrictorTest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentTestBase.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/support/MyRestrictor.java, components-starter/pom.xml, pom.xml, tooling/camel-spring-boot-bom/pom.xml, tooling/camel-spring-boot-dependencies/pom.xml
cherry pick faa1fcc148fac24f1cc3675fa42cb757e3f6d119 372c7a9be8444c5cbafba3ab0cbfaa106272dfa9
=> Jolokia starter on 4.8

components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpAutoConfiguration.java, components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpMultipleExecutorsTest.java
=> CAMEL-21419: Handle Multiple Executors

pom.xml
Upgrade spring-boot to 3.3.6 on the camel-spring-boot-4.8.x branch.
=> Upgrade spring-boot to 3.3.6

pom.xml
it aligns with version in Camel Core
=> chore: Upgrade Maven CycloneDX plugin to 2.9.1

pom.xml
it aligns with version in Camel Core
https://github.com/apache/camel/blob/5fe84bcb4269061f057b296a6b53ddda8e6d1f72/pom.xml#L135
=> chore: Upgrade Maven surefire plugin to 3.5.2

components-starter/camel-jolokia-starter/src/main/docs/jolokia.adoc, components-starter/camel-jolokia-starter/src/main/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfiguration.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationDiscoveryDisabledTest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationOnK8STest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentAutoConfigurationTest.java, components-starter/camel-jolokia-starter/src/test/java/org/apache/camel/component/jolokia/springboot/JolokiaComponentTestBase.java
Cherry pick changes from https://github.com/apache/camel-spring-boot/commit/09c6c6d498d7f41086095d94b547735f46afbbc8 back to camel-spring-boot-4.8.x branch for 4.8.3 
Ran tests on components-starter/camel-jolokia-starter and they passed
=> camel-jolokia-starter: Enables discovery on local environment

components-starter/camel-micrometer-starter/src/main/docs/micrometer.json, components-starter/camel-micrometer-starter/src/main/java/org/apache/camel/component/micrometer/springboot/metrics/CamelMetricsAutoConfiguration.java, components-starter/camel-micrometer-starter/src/main/java/org/apache/camel/component/micrometer/springboot/metrics/CamelMetricsConfiguration.java
=> feat(components/micrometer): baseEndpointUriExchangeEventNotifier parameter

pom.xml, tooling/camel-spring-boot-bom/pom.xml, tooling/camel-spring-boot-dependencies/pom.xml
Update the 4.8.x branch to spring-boot 3.3.10; did a mvn -DskipTests clean install and it picked some refresh files
=> Update spring-boot to 3.3.10; refresh (version update)

.gitignore
Adding the output of the maven build metada plugin to the gitignore file
=> Add the output of the maven build metadata plugin to the gitignore file

catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/components/jetty.json, catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/components/undertow.json, components-starter/camel-jetty-starter/pom.xml, components-starter/camel-undertow-starter/pom.xml
https://issues.apache.org/jira/browse/CAMEL-21573
=> CAMEL-21573 camel-spring-boot - Deprecate jetty and undertow starter

pom.xml
Upgrade spring-boot to 3.4.7, also bump spring-session-hazelcast to 3.4.4
=> Upgrade spring-boot to 3.4.7

pom.xml
Upgrade to spring-boot 3.3.13; upgrade cyclonedx and spring-session-hazelcast to match spring-boot versions (and fix spacing of the cyclonedx property)
=> Upgrade to spring-boot 3.3.13

components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpBridgedEndpointTest.java
test for https://github.com/apache/camel/pull/18755
=> CAMEL-22282: Test for platform-http bridged endpoint

components-starter/camel-debug-starter/src/main/docs/debug.json, core/camel-spring-boot/src/main/docs/spring-boot.json, pom.xml
Upgrade to spring-boot 3.5.5 (camel-spring-boot-4.14.x)
=> Upgrade to spring-boot 3.5.5; refresh

components-starter/camel-jolokia-starter/src/main/docs/jolokia.adoc
update documentation according to https://github.com/jolokia/jolokia/issues/834
=> camel-jolokia-starter: update exposed enpoint

catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/others.properties, catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/others/micrometer-observability.json, components-starter/camel-micrometer-observability-starter/pom.xml, components-starter/camel-micrometer-observability-starter/src/main/docs/micrometer-observability.json, components-starter/camel-micrometer-observability-starter/src/main/java/org/apache/camel/micrometer/observability/starter/CamelMicrometerObservability.java, components-starter/camel-micrometer-observability-starter/src/main/java/org/apache/camel/micrometer/observability/starter/MicrometerObservabilityAutoConfiguration.java, components-starter/camel-micrometer-observability-starter/src/main/java/org/apache/camel/micrometer/observability/starter/MicrometerObservabilityConditionalAutoConfiguration.java, components-starter/camel-micrometer-observability-starter/src/main/java/org/apache/camel/micrometer/observability/starter/MicrometerObservabilityConfigurationProperties.java, components-starter/camel-micrometer-observability-starter/src/main/resources/META-INF/LICENSE.txt, components-starter/camel-micrometer-observability-starter/src/main/resources/META-INF/NOTICE.txt, components-starter/camel-micrometer-observability-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, components-starter/pom.xml, tooling/camel-spring-boot-bom/pom.xml, tooling/camel-spring-boot-dependencies/pom.xml
=> feat(starters): onboard Micrometer Observability starter

components-starter/camel-platform-http-starter/pom.xml, components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/actuate/metrics/undertow/UndertowComponents.java, components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/actuate/metrics/undertow/UndertowMetrics.java, components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/actuate/metrics/undertow/UndertowMetricsAutoConfiguration.java, components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/actuate/metrics/undertow/UndertowMetricsBinder.java, components-starter/camel-platform-http-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, components-starter/camel-platform-http-starter/src/test/resources/application.properties
=> Undertow metrics

pom.xml
Upgrade spring-boot to 3.4.10
Also upgrade spring-session-hazelcast to most recent 3.4.x version
=> Upgrade spring-boot to 3.4.10

components-starter/camel-file-cluster-service-starter/src/main/docs/file-cluster-service.json, components-starter/camel-file-cluster-service-starter/src/main/java/org/apache/camel/component/file/springboot/cluster/FileLockClusterServiceAutoConfiguration.java, components-starter/camel-file-cluster-service-starter/src/main/java/org/apache/camel/component/file/springboot/cluster/FileLockClusterServiceConfiguration.java
Companion to https://github.com/apache/camel/pull/19272.
=> CAMEL-22430: Add heartbeatTimeoutMultiplier configuration option to camel-file-cluster-service-starter

components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/Utils.java
cherry-pick https://github.com/apache/camel-spring-boot/commit/45a7c22b044c2174c63b08f307bfe7d6029eb59c due to https://github.com/apache/camel/pull/19369
=> Upgrade jira 6.0.2

catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/others.properties, catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/others/mdc.json, components-starter/camel-mdc-starter/pom.xml, components-starter/camel-mdc-starter/src/main/docs/mdc.json, components-starter/camel-mdc-starter/src/main/java/org/apache/camel/mdc/starter/CamelMDC.java, components-starter/camel-mdc-starter/src/main/java/org/apache/camel/mdc/starter/MDCAutoConfiguration.java, components-starter/camel-mdc-starter/src/main/java/org/apache/camel/mdc/starter/MDCConfigurationProperties.java, components-starter/camel-mdc-starter/src/main/resources/META-INF/LICENSE.txt, components-starter/camel-mdc-starter/src/main/resources/META-INF/NOTICE.txt, components-starter/camel-mdc-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, components-starter/pom.xml, tooling/camel-spring-boot-bom/pom.xml, tooling/camel-spring-boot-dependencies/pom.xml
Requires https://github.com/apache/camel/pull/19297 to be merged
=> feat(starters): add mdc component
