apache/camel-spring-boot

- components-starter/camel-undertow-spring-security-starter/src/main/java/org/apache/camel/undertow/spring/boot/UndertowSpringSecurityAutoConfiguration.java
- components-starter/camel-undertow-spring-security-starter/src/main/java/org/apache/camel/undertow/spring/boot/UndertowSpringSecurityConfiguration.java
- components-starter/camel-undertow-spring-security-starter/src/main/java/org/apache/camel/undertow/spring/boot/providers/AbstractProviderConfiguration.java
- components-starter/camel-undertow-spring-security-starter/src/main/java/org/apache/camel/undertow/spring/boot/providers/KeycloakProviderConfiguration.java
- examples/camel-example-spring-boot-undertow-spring-security/src/main/java/org/apache/camel/undertow/spring/boot/Application.java
Replaces usage of constant "preferred_username" with getProvider().getUserNameAttribute().
Renames package name in starter by omitting "example".
> Fixing name of package and use of property instead of constant

- examples/camel-example-spring-boot-widget-gadget/pom.xml
- examples/camel-example-spring-boot-widget-gadget/src/main/data/order1.json
- examples/camel-example-spring-boot-widget-gadget/src/main/data/order2.json
- examples/camel-example-spring-boot-widget-gadget/src/main/java/sample/camel/AmqpConfig.java
- examples/camel-example-spring-boot-widget-gadget/src/main/java/sample/camel/OrderRoute.java
- examples/camel-example-spring-boot-widget-gadget/src/main/java/sample/camel/WidgetGadgetApp.java
- examples/camel-example-spring-boot-widget-gadget/src/main/java/sample/camel/WidgetGadgetRoute.java
- examples/camel-example-spring-boot-widget-gadget/src/main/resources/application.properties
- examples/pom.xml
Classical widget-gadget integration example from the EIP book, running on SpringBoot and using AMQP and JSONPath.
> Widget gadget example

- components-starter/camel-consul-starter/src/main/docs/consul-starter.adoc
- components-starter/camel-consul-starter/src/main/java/org/apache/camel/component/consul/springboot/cloud/ConsulServiceRegistryConfiguration.java
- components-starter/camel-consul-starter/src/main/java/org/apache/camel/component/consul/springboot/cluster/ConsulClusterServiceConfiguration.java
Copied properties from parent classes to include javadoc because
spring-boot-configuration-processor detects inherited properties by their public
getters/setters but can not find the corresponding javadoc used for descriptions in
generated adoc
> [CAMEL-14565]: Copied fields from parent class to include javadoc description of spring config properties

- components-starter/camel-undertow-spring-security-starter/src/main/java/org/apache/camel/undertow/spring/boot/providers/KeycloakProviderConfiguration.java
The corresponding jwt claim is `preferred_username` in keycloak, not `preffered_username`
> Corrected userNameAttribute default

- components-starter/camel-jasypt-starter/pom.xml
- components-starter/camel-jasypt-starter/src/main/docs/jasypt-starter.adoc
- components-starter/camel-jasypt-starter/src/main/java/org/apache/camel/component/jasypt/springboot/EncryptablePropertySourcesPlaceholderConfigurer.java
- components-starter/camel-jasypt-starter/src/main/java/org/apache/camel/component/jasypt/springboot/JasyptEncryptedPropertiesAutoconfiguration.java
- components-starter/camel-jasypt-starter/src/main/java/org/apache/camel/component/jasypt/springboot/JasyptEncryptedPropertiesConfiguration.java
- components-starter/camel-jasypt-starter/src/main/java/org/apache/camel/component/jasypt/springboot/JasyptEncryptedPropertiesUtils.java
- components-starter/camel-jasypt-starter/src/main/java/org/apache/camel/component/jasypt/springboot/JasyptSpringEncryptedPropertiesParser.java
- components-starter/camel-jasypt-starter/src/main/resources/META-INF/spring.factories
- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/Constants.java
- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/EncryptedProperiesTestBase.java
- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/EncryptedPropertiesBean.java
- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/EncryptedPropertiesCustomConfigurationBeansTest.java
- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/EncryptedPropertiesDisabledCustomConfigurationBeansTest.java
- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/EncryptedPropertiesDisabledTest.java
- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/EncryptedPropertiesTest.java
- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/Routes.java
- components-starter/camel-jasypt-starter/src/test/resources/application.properties
- components-starter/camel-jasypt-starter/src/test/resources/logback.xml
- core/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/CamelAutoConfiguration.java
Added auto-configuration that registers the necessary beans to allow properties decryption inside and outside the camel context.
> CAMEL-15541: Add auto-configuration to camel-jasypt-starter

- dsl-starter/camel-java-joor-dsl-starter/pom.xml
- dsl-starter/camel-xml-io-dsl-starter/pom.xml
- dsl-starter/camel-xml-jaxb-dsl-starter/pom.xml
- dsl-starter/camel-yaml-dsl-starter/pom.xml
Use `camel-version` for Camel core dependencies to avoid issues during the release process.
> Use camel-version for Camel core dependencies

- catalog/pom.xml
- core/pom.xml
- parent/pom.xml
- pom.xml
- tests/pom.xml
- tooling/camel-spring-boot-bom-generator/target-template-pom.xml
- tooling/camel-spring-boot-bom/pom.xml
- tooling/pom.xml
When attempting to release Camel Spring Boot 3.4.6, I hit the same issue regarding the parent pom restructuring as we previously faced with the 3.7.1 release.
In this PR, I applied the relevant changes from PR https://github.com/apache/camel-spring-boot/pull/262 onto the `camel-spring-boot-3.4.x` branch.
> CAMEL-16055: Add spring-boot-parent pom.xml

- docs/README_local_build.adoc
- docs/local-build.sh
- docs/source-map.yml
- docs/source-watch.yml
Sets up new docs local-build for camel-spring-boot 3.13.x. See apache/camel-website#731
> Camel spring boot 3.13.x local build v2

- docs/README_local_build.adoc
- docs/local-build.sh
- docs/source-map.yml
- docs/source-watch.yml
Sets up new docs local-build for camel-spring-boot 3.12.x. See apache/camel-website#731
> Camel spring boot 3.12.x local build v2

- docs/README_local_build.adoc
- docs/local-build.sh
- docs/source-map.yml
- docs/source-watch.yml
Sets up new docs local-build for camel-spring-boot 3.11.x. See apache/camel-website#731
> Camel spring boot 3.11.x local build v2

- docs/README_local_build.adoc
- docs/local-build.sh
- docs/source-map.yml
- docs/source-watch.yml
Sets up new docs local-build for camel-spring-boot 3.7.x. See apache/camel-website#731
> Camel spring boot 3.7.x local build v2

- components-starter/camel-mongodb-starter/pom.xml
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/AbstractMongoDbITSupport.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbAggregateOperationIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbBigDecimalConverterIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbBulkWriteOperationIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbChangeStreamsConsumerIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbConnectionBeansIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbConversionsIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbCredentialsFromUriConnectionIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbDynamicityIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbExceptionHandlingIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbFindOperationIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbHeaderHandlingIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbIndexIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbInsertBatchIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbOperationsIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbOutputTypeIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbReadPreferenceOptionIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbSpringDslOperationsIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbStopEndpointIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbTailableCursorConsumerIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/meta/integration/MongoDbMetaExtensionIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/processor/idempotent/MongoDbIdempotentRepositoryIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/verifier/integration/MongoDbVerifierExtensionIT.java
- components-starter/camel-mongodb-starter/src/test/resources/log4j2.properties
- components-starter/camel-mongodb-starter/src/test/resources/mongodb.test.properties
- components-starter/camel-mongodb-starter/src/test/resources/org/apache/camel/component/mongodb/mongoBasicOperationsTest.xml
@ffang 
I'm sorry for 4k+ lines of code addition, this is a porting of tests from camel to camel-spring-boot, in order to use springboot as runtime some changes were needed in particular in AbstractMongoDbITSupport
> [CAMEL-17801] Add tests in camel-mongodb-starter

- components-starter/camel-google-bigquery-starter/pom.xml
https://issues.apache.org/jira/browse/CAMEL-17884
> CAMEL-17884 Guava is overriden to an older version in bigquery starter

- components-starter/camel-aws2-sqs-starter/pom.xml
- components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/BaseSqs.java
- components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/JmsStyleSelectorTest.java
- components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/SqsComponentTest.java
- components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/SqsDeadletterTest.java
- components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/SqsDelayedQueueTest.java
- components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/SqsOperationsTest.java
- components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/SqsProducerAutoCreateQueueTest.java
- components-starter/camel-aws2-sqs-starter/src/test/resources/org/apache/camel/component/aws2/sqs/policy.txt
Issue https://issues.apache.org/jira/browse/CAMEL-17860
There are 2 topics, which are not covered by this PR - [SERVER SIDE ENCRYPTION](https://camel.apache.org/components/3.16.x/aws2-sqs-component.html#_server_side_encryption) and [SEND BATCH MESSAGE AND MESSAGE DEDUPLICATION STRATEGY](https://camel.apache.org/components/3.16.x/aws2-sqs-component.html#_send_batch_message_and_message_deduplication_strategy). 
I reported missing (or not correct) tests in camel component - see https://issues.apache.org/jira/browse/CAMEL-17904
> CAMEL-17860 add tests in camel-aws2-sqs-starter

- core/camel-spring-boot/src/main/docs/starter-configuration.adoc
Fix for https://issues.apache.org/jira/browse/CAMEL-17964 (part 2)
The build of the [website fails](https://ci-builds.apache.org/job/Camel/job/Camel.website/job/main/827/console) due to an incorrect link [even with the latest fix ](https://github.com/apache/camel-spring-boot/commit/73338c94297f1b0d5137b946874290e2f1f3549c)
* Add missing sub section components to the link
> CAMEL-17964: Fix the link to the doc page main.adoc

- components-starter/camel-aws2-sqs-starter/pom.xml
- components-starter/camel-aws2-sqs-starter/src/test/java/org/apache/camel/component/aws2/sqs/SqsOperationsTest.java
Was getting a class not found error on org.testcontainers.shaded.org.apache.commons.lang.RandomStringUtils - replace with commons-lang version and add in commons-lang dependency
> Use commons-lang for aws2-sqs-starter

- components-starter/camel-kafka-starter/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAsyncManualCommitIT.java
Test was annotated out here in camel --
https://github.com/apache/camel/commit/2589086ba6a76083ffc95790621277f45078e7a2
Test is also failing in camel-spring-boot - annotating it out
> chore: Fix integration test failure by not running test by default

- tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelWebhookTest.java
https://issues.apache.org/jira/browse/CAMEL-17987
Temporarily disable CamelWebhookTest - throwing a log4j-slf4j-impl cannot be present with log4j-to-slf4j error - I think it needs some exclusions or other configuration in createTestConfig() - not sure why this is the only Spring Boot test exhibiting this error
> CAMEL-17987 Temporarily disable CamelWebhookTest (log4j-slf4j-impl cannot be present with log4j-to-slf4j)

- .github/workflows/pr-build.yml
We're getting failures in some of the integration tests but the build.log stored by the PR job does not have a lot of detail to go on -
Example, from CamelSqlTest failure in one of the recent PR build runs -
```
[ERROR] org.apache.camel.itest.springboot.CamelSqlTest.componentTests  Time elapsed: 25.465 s  <<< ERROR!
java.lang.Exception: 
Caused by: org.opentest4j.AssertionFailedError: Some unit tests failed (1/25), check the logs for more details
```
I'd like to temporarily start archiving the surefire logs to see if we could diagnose the failures - I'm not sure whether this is going to give us additional information or not.    I haven't been able to reproduce these failures locally.     
I think we can expire the logs pretty quickly so that they don't take up a lot of space.
> Archive surefire logs to try to diagnose integration test failures

- tooling/camel-spring-boot-dependencies/pom.xml
- tooling/camel-spring-boot-generator-maven-plugin/src/main/java/org/apache/camel/springboot/maven/BomDependenciesGeneratorMojo.java
Set correct type to camel-*-parent flattened dependencies.
@cunningt 
@davsclaus @oscerd Hello, I remember some discussions around camel-spring-boot-dependencies bom deprecation, do you still think that camel-spring-boot-bom should be used instead of -dependencies?
> Set pom type to parent deps

- components-starter/camel-master-starter/pom.xml
- components-starter/camel-telegram-starter/pom.xml
- components-starter/camel-webhook-starter/pom.xml
I think we can remove the references to camel-test-junit5 in the few components that bring it in.     components-starter brings in camel-spring-test-junit5 already, which all of the components starters inherit from.
Ran the tests on these components, saw no errors.
> Remove camel-test-junit5 - components-starter already brings in camel-spring-test-junit5

- components-starter/camel-aws2-sns-starter/src/test/java/org/apache/camel/component/aws2/sns/SnsComponentFifoTest.java
- components-starter/camel-aws2-sns-starter/src/test/java/org/apache/camel/component/aws2/sns/SnsTopicWithKmsEncryptionTest.java
- components-starter/camel-bean-validator-starter/src/test/java/org/apache/camel/component/bean/validator/springboot/BeanValidatorRouteTest.java
- components-starter/camel-bindy-starter/src/test/java/org/apache/camel/dataformat/bindy/springboot/csv/BindySimpleCsvUnmarshallBadIntegerTest.java
- components-starter/camel-bindy-starter/src/test/java/org/apache/camel/dataformat/bindy/springboot/csv/BindySimpleCsvUnmarshallPositionModifiedTest.java
- components-starter/camel-bindy-starter/src/test/java/org/apache/camel/dataformat/bindy/springboot/csv/BindySimpleCsvUnmarshallTest.java
- components-starter/camel-bindy-starter/src/test/java/org/apache/camel/dataformat/bindy/springboot/fixed/BindySimpleFixedLengthMarshallWithNoClipTest.java
- components-starter/camel-cassandraql-starter/src/test/java/org/apache/camel/component/cassandra/integration/CassandraComponentProducerIT.java
- components-starter/camel-cassandraql-starter/src/test/java/org/apache/camel/component/cassandra/integration/CassandraComponentProducerUnpreparedIT.java
- components-starter/camel-gson-starter/src/test/java/org/apache/camel/component/gson/springboot/GsonConcurrentTest.java
- components-starter/camel-hl7-starter/src/test/java/org/apache/camel/component/hl7/springboot/test/HL7ValidateTest.java
- components-starter/camel-jackson-starter/src/test/java/org/apache/camel/component/jackson/springboot/test/JacksonConcurrentTest.java
- components-starter/camel-jackson-starter/src/test/java/org/apache/camel/component/jackson/springboot/test/JacksonObjectListSplitTest.java
- components-starter/camel-jacksonxml-starter/src/test/java/org/apache/camel/component/jacksonxml/springboot/JacksonConcurrentTest.java
- components-starter/camel-jacksonxml-starter/src/test/java/org/apache/camel/component/jacksonxml/springboot/JacksonObjectListSplitTest.java
- components-starter/camel-jaxb-starter/src/test/java/org/apache/camel/converter/jaxb/springboot/JaxbConcurrentDataFormatTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/AddIssueLinkProducerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/AddWorkLogProducerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/FetchCommentsProducerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/FetchIssueProducerTest.java
- components-starter/camel-quartz-starter/src/test/java/org/apache/camel/component/quartz/springboot/QuartzManagementTest.java
- components-starter/camel-saxon-starter/src/test/java/org/apache/camel/language/xquery/springboot/XQueryConcurrencyTest.java
- components-starter/camel-saxon-starter/src/test/java/org/apache/camel/language/xquery/springboot/XQueryURLBasedConcurrencyTest.java
- components-starter/camel-sql-starter/src/test/java/org/apache/camel/component/sql/SqlProducerExpressionParameterTest.java
- components-starter/camel-sql-starter/src/test/java/org/apache/camel/component/sql/SqlProducerUseMessageBodyForSqlTest.java
- components-starter/camel-sql-starter/src/test/java/org/apache/camel/component/sql/SqlTransactedRouteTest.java
- components-starter/camel-telegram-starter/src/test/java/org/apache/camel/component/telegram/springboot/TelegramChatBotTest.java
- components-starter/camel-telegram-starter/src/test/java/org/apache/camel/component/telegram/springboot/TelegramConsumerFallbackConversionTest.java
- components-starter/camel-telegram-starter/src/test/java/org/apache/camel/component/telegram/springboot/TelegramConsumerMediaPhotoTest.java
Remove unused imports of org.apache.camel.test.junit5.*, simplify some of the asserts by trying to use junit api asserts
> Remove unused imports, simplify asserts

- archetypes/camel-archetype-spring-boot/pom.xml
- archetypes/camel-archetype-spring-boot/src/test/resources/settings.xml
Two fixes here :
- Remove unnecessary duplicated property - the archetype spring-boot-version property seems unnecessary due to the parent structure
- Change the repository in the archetype settings.xml to https:// to avoid the maven 3.8.1 "Blocked mirror for repositories" error
> Remove unnecessary duplicated property, and change the archetype repository to https

- archetypes/camel-archetype-spring-boot/pom.xml
- pom.xml
Update to latest Spring Boot 2.6.x GA version before releasing Camel 3.14.4
> Update to Spring Boot 2.6.8

- components-starter/camel-slack-starter/pom.xml
Use `${project.version}` of the undertow-starter for testing rather than ${camel-version} - `${camel-version}` should only apply to camel project artifacts
> Use ${project.version} of the undertow-starter for testing rather than ${camel-version}

- pom.xml
https://spring.io/blog/2022/06/23/spring-boot-2-7-1-available-now was released
> Update to SB 2.7.1

- components-starter/camel-guava-eventbus-starter/pom.xml
- tooling/camel-spring-boot-generator-maven-plugin/src/main/resources/spring-boot-fix-dependencies.properties
camel-guava-eventbus-starter should be using the same version the camel-guava-eventbus component is using --
https://github.com/apache/camel/blob/main/components/camel-guava-eventbus/pom.xml#L45
> Align guava version used by starter with camel-guava-eventbus component

- components-starter/camel-platform-http-starter/pom.xml
- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/ServletPlatformHttpAutoConfiguration.java
- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/ServletPlatformHttpEngine.java
- components-starter/camel-platform-http-starter/src/main/resources/META-INF/spring.factories
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/ServletPlatformHttpBase.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/ServletPlatformHttpRestDSLTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/ServletPlatformHttpTest.java
The idea behind this PR is to use camel-platform-http-starter and camel-servlet-starter without any additional configuration.
If camel-servlet is configured in the context (camel-servlet-starter is declared as a dependency), then a PlatformHttpEngine implementation is created using the servlet, I'm not 100% sure about the reflection, if you think it can be done in some other way please let me know.
> ✨ CAMEL-18449 platform-http servlet implementation

- tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelMongodbGridfsTest.java
- tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelMongodbTest.java
These two integration tests were failing last week, and it looks like the reason is the specified version of the mongodb driver, which is now 4.6.0 (https://github.com/apache/camel/blob/main/parent/pom.xml#L400).      I've tried locally and it doesn't seem necessary to specify the version of the dependencies - these tests pass locally for me without the version specified.
> Remove driver version from mongodb dependencies in tests

- archetypes/camel-archetype-spring-boot/pom.xml
- pom.xml
https://github.com/apache/camel/pull/8444 is the camel side PR to align to spring-boot 2.6.12 spring-boot-dependencies
> Align to spring-boot 2.6.12

- pom.xml
Cherry pick upgrade of spring-boot to 2.7.4 over the LTS branch
> Align to spring-boot 2.7.4 (#637)

- components-starter/camel-cxf-soap-starter/src/test/java/org/apache/camel/component/cxf/soap/springboot/wssecurity/WSSecurityRouteTest.java
with the default constructor, the location _file:/home/jenkins/workspace/Camel_Daily_Snapshot_Deploy_main/components/camel-cxf/camel-cxf-spring-soap/src/test/resources/hello_world_wssec.wsdl_ will be used
> CAMEL-18729 - Fix GreeterService default WSDL URL in test

- components-starter/camel-gson-starter/src/test/java/org/apache/camel/component/gson/springboot/GsonFieldNamePolicyTest.java
- components-starter/camel-gson-starter/src/test/java/org/apache/camel/component/gson/springboot/GsonMarshalExclusionTest.java
- components-starter/camel-gson-starter/src/test/java/org/apache/camel/component/gson/springboot/SpringGsonFieldNamePolicyTest.java
Flaky Tests found using [NonDex](https://github.com/TestingResearchIllinois/NonDex) by running the commands -
`
mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.camel.component.gson.springboot.GsonFieldNamePolicyTest#testMarshalPojo
`
`
mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.camel.component.gson.springboot.GsonMarshalExclusionTest#testMarshalAndUnmarshalPojoWithAnotherExclusion
`
`
mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.camel.component.gson.springboot.SpringGsonFieldNamePolicyTest#testMarshalPojo
`
The logged failures were-
```
[WARNING] Flakes: 
[WARNING] org.apache.camel.component.gson.springboot.GsonFieldNamePolicyTest.testMarshalPojo
[ERROR]   Run 1: GsonFieldNamePolicyTest.testMarshalPojo:76 expected: …
```
> Fixed Flaky Tests Caused by JSON permutations

- components-starter/camel-gson-starter/src/test/java/org/apache/camel/component/gson/springboot/GsonMarshalExclusionTest.java
Flaky Tests found using [NonDex](https://github.com/TestingResearchIllinois/NonDex) by running the commands -
`
mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.camel.component.gson.springboot.GsonMarshalExclusionTest#testMarshalAndUnmarshalPojoWithExclusion
`
The logged failure was-
```
[WARNING] Flakes:
[WARNING] org.apache.camel.component.gson.springboot.GsonMarshalExclusionTest.testMarshalAndUnmarshalPojoWithExclusion
[ERROR]   Run 1: GsonMarshalExclusionTest.testMarshalAndUnmarshalPojoWithExclusion:80 expected: <{"age":30,"height":190}> but was: <{"height":190,"age":30}>
```
The tests  fail with a comparison error while comparing an expected JSON String and the result from the value returned by the funtion template.requestBody(...). The function of the that …
> Fixed Flaky Test Caused by JSON permutations

- components-starter/camel-swift-starter/pom.xml
Add version element to JUnit dependency in `camel-swift-starter` to avoid build failure when releasing.
> Add version element to JUnit dependency

- catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/others/undertow-spring-security.json
- components-starter/camel-undertow-spring-security-starter/pom.xml
- components-starter/camel-undertow-spring-security-starter/src/main/docs/undertow-spring-security.json
- components-starter/camel-undertow-spring-security-starter/src/main/java/org/apache/camel/undertow/spring/boot/UndertowSpringSecurityConfiguration.java
- components-starter/camel-undertow-spring-security-starter/src/main/java/org/apache/camel/undertow/spring/boot/UndertowSpringSecurityCustomizer.java
- components-starter/camel-undertow-spring-security-starter/src/main/java/org/apache/camel/undertow/spring/boot/providers/AbstractProviderConfiguration.java
- components-starter/camel-undertow-spring-security-starter/src/main/java/org/apache/camel/undertow/spring/boot/providers/KeycloakProviderConfiguration.java
- components-starter/camel-undertow-spring-security-starter/src/main/resources/META-INF/LICENSE.txt
- components-starter/camel-undertow-spring-security-starter/src/main/resources/META-INF/NOTICE.txt
- components-starter/camel-undertow-spring-security-starter/src/main/resources/META-INF/spring.provides
- components-starter/pom.xml
- tooling/camel-spring-boot-bom/pom.xml
- tooling/camel-spring-boot-dependencies/pom.xml
This reverts commit a1b2af71dace2279b5743a4d0fc3921f6d0f8bfe.
CAMEL-18984 camel-undertow-spring-security-starter - Migrate to Spring Boot 3
> CAMEL-18984 camel-undertow-spring-security-starter - Migrate to Spring Boot 3

- components-starter/camel-undertow-spring-security-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Hello @davsclaus @Kinae I've added AutConfiguration.imports for both configuration classes, though I don't fully understand why https://github.com/apache/camel-spring-boot/pull/721/files#diff-47c8b6bf12f1a4c3f116d1e2c09fa7451f9fbbac7a3adc1c248c07be11b55cfbR31 is not annotated with Configuration. An example with this starter would be nice to have.
> CAMEL-18984: Add autoconfigure imports

- components-starter/camel-aws2-s3-starter/src/test/java/org/apache/camel/component/aws2/s3/S3CreateDownloadLinkOperationTest.java
Changing the length of the password by at least 16 bytes, allows test execution in FIPS enabled environments
> Make S3CreateDownloadLinkOperationTest FIPS compliant

- pom.xml
Update to Spring Boot 3.0.4.
The PR for the corresponding dependency updates for Camel core is here: https://github.com/apache/camel/pull/9467.
> CAMEL-19110: Upgrade Spring Boot to 3.0.4

- parent/pom.xml
As far as I can find camel-core-engine-starter doesn't exist and I can't find it ever deployed - I think it is okay to remove?
> Remove camel-core-engine-starter - does not exist

- components-starter/camel-openapi-java-starter/pom.xml
- components-starter/camel-openapi-java-starter/src/main/java/org/apache/camel/springboot/openapi/OpenApiAutoConfiguration.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/ComplexTypesTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiModelApiSecurityRequirementsTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderApiDocsOverrideTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderApiDocsTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderContextPathTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderDayOfWeekTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderEnableVendorExtensionTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderFileResponseModelTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderModelApiSecurityTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderModelBookOrderTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderModelTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderOverrideHostApiDocsTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderPropertyPlaceholderTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiV2SecuritySchemesTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiV3SecuritySchemesTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/SpringRestOpenApiReaderModelApiSecurityTest.java
- components-starter/camel-openapi-java-starter/src/test/resources/application.properties
- components-starter/camel-openapi-java-starter/src/test/resources/logback.xml
- components-starter/camel-openapi-java-starter/src/test/resources/org/apache/camel/openapi/V2SchemaForComplexTypesRequest.json
- components-starter/camel-openapi-java-starter/src/test/resources/org/apache/camel/openapi/V2SchemaForComplexTypesResponse.json
- components-starter/camel-openapi-java-starter/src/test/resources/org/apache/camel/openapi/V3SchemaForComplexTypesRequest.json
- components-starter/camel-openapi-java-starter/src/test/resources/org/apache/camel/openapi/V3SchemaForComplexTypesResponse.json
- components-starter/camel-springdoc-starter/src/main/java/org/apache/camel/springboot/springdoc/SpringdocAutoConfiguration.java
Modify the AutoConfiguration classes to use the modified return type in RestOpenApiReader.read method. Since OpenAPI is now directly returned there is no need to convert it to json and reparse it with swagger. In addition, this change allows handling of an OpenAPI 2.x specification which will be automatically upgraded to OpenAPI 3.x. Previously this would have failed due to the direct use of OpenAPIV3Parser.
> CAMEL-18963: upgrade both spring-boot starters using camel-openapi-java

- components-starter/camel-kafka-starter/src/test/java/org/apache/camel/component/kafka/integration/KafkaProducerFullIT.java
The build fails due to some tests that must be fixed
* Makes the method annotated with `@AfterAll` static as expected by JUnit to prevent runtime error
* Resets the mock endpoint after each test to better match with the context
> camel-kafka - Properly define the after all method

- components-starter/camel-kafka-starter/src/test/java/org/apache/camel/component/kafka/integration/KafkaProducerFullIT.java
The test `KafkaProducerFullIT#producedBytesMessageIsReceivedByKafka` fails due to a `TimeoutException` with the message `Topic testBytes not present in metadata after 60000 ms`.
* Set the correct id of the existing partition which is `0`
> camel-kafka - Set the correct partition id

- components-starter/camel-salesforce-starter/pom.xml
- components-starter/camel-salesforce-starter/src/test/java/org/apache/camel/component/salesforce/springboot/RawPayloadTest.java
The test `RawPayloadTest` in `camel-salesforce` fails due to the exception `NoSuchMethodError: 'void okhttp3.internal.Internal.initializeInstanceForTests()'`
* Adds the missing test dependency based on https://github.com/apache/camel/blob/main/components/camel-salesforce/camel-salesforce-component/pom.xml#L237-L243
* Adds the id to the fake payload response to avoid an NPE when [extracting the `orgId`](https://github.com/apache/camel/blob/main/components/camel-salesforce/camel-salesforce-component/pom.xml#L237-L243)
> camel-salesforce - Add missing test dependency and id

- components-starter/camel-zookeeper-starter/src/test/java/org/apache/camel/component/zookeeper/springboot/cloud/ZooKeeperServiceRegistryTest.java
- tests/camel-itest-spring-boot/README.adoc
- tests/camel-itest-spring-boot/pom.xml
- tests/camel-itest-spring-boot/src/main/java/org/apache/camel/itest/springboot/ITestConfig.java
- tests/camel-itest-spring-boot/src/main/java/org/apache/camel/itest/springboot/ITestConfigBuilder.java
- tests/camel-itest-spring-boot/src/main/java/org/apache/camel/itest/springboot/command/AbstractTestCommand.java
- tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelAmqpTest.java
- tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelCordaTest.java
- tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelCxfRestTest.java
- tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelCxfSoapTest.java
- tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelJpaTest.java
- tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelSnakeyamlTest.java
- tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelSwiftTest.java
- tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/util/ArquillianPackager.java
Many integration tests fail mostly due to a version conflict issue. The goal of this PR is to get green build again before fixing the remaining problems.
* Allows logging warnings instead of failing in case of a version conflict issue by configuration
* Disables temporary the failures in case of a version conflict
* Cleans up the Zookeeper integration test
* Splits the CXF integration tests in two (soap and rest)
* Disables temporary the SnakeYAML integration test due to a conflict between v 1.3 and 2
* Adds an integration test for the Swift component
* Fixes a violations
> camel-itest - Allow to log a warning on version conflict

- components-starter/camel-ftp-starter/src/test/java/org/apache/camel/component/file/remote/springboot/ftps/FileToFtpsImplicitSSLWithClientAuthTest.java
- components-starter/camel-ftp-starter/src/test/java/org/apache/camel/component/file/remote/springboot/ftps/FileToFtpsWithCustomTrustStorePropertiesTest.java
- components-starter/camel-ftp-starter/src/test/java/org/apache/camel/component/file/remote/springboot/ftps/FtpsTest.java
- components-starter/camel-ftp-starter/src/test/java/org/apache/camel/component/file/remote/springboot/sftp/SftpConsumerLocalWorkDirectoryTest.java
- components-starter/camel-ftp-starter/src/test/java/org/apache/camel/component/file/remote/springboot/sftp/SftpKeyExchangeProtocolsTest.java
- components-starter/camel-ftp-starter/src/test/java/org/apache/camel/component/file/remote/springboot/sftp/SftpUseListFalseTest.java
The Spring Boot configuration is executed before the ftp server configuration and the results are wrong route configurations (wrong default ftp server port), due to the ftp server initialization on each test.
Now the failure test classes add the routes to the Camel context before each test, when the ftp server is already configured and the port number is correctly set
> FTP tests fixes, routes lazy loading, after server config

- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/PlatformHttpBase.java
Those tests must be executed only from inheritor classes
> Avoid test execution of PlatformHttpBase class

- components-starter/camel-springdoc-starter/pom.xml
- components-starter/camel-springdoc-starter/src/main/java/org/apache/camel/springboot/springdoc/SpringdocAutoConfiguration.java
- pom.xml
Replace springdoc-openapi-ui with springdoc-openapi-starter-webmvc-ui. Update version in the parent pom.
Remove swagger-parser-v3 dependency since it is provided by camel-openapi-java. Fix missing assignment in SpringdocAutoConfiguration.java.
> CAMEL-19793: update dependencies.

- components-starter/camel-kafka-starter/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerHealthCheckIT.java
Related to https://issues.apache.org/jira/browse/CAMEL-19854
The test KafkaConsumerHealthCheckIT always fails on the CI.
* Disable the test as long as it is not fixed
> CAMEL-19854: camel-kafka - Disable the test KafkaConsumerHealthCheckIT

- components-starter/camel-kafka-starter/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentTestSupport.java
Fixes https://issues.apache.org/jira/browse/CAMEL-19861
The test `KafkaConsumerIdempotentWithProcessorIT` fails randomly on the CI.
* Increase the result wait time to 20 seconds
> CAMEL-19861: camel-kafka - Increase the result wait time

- components-starter/camel-kamelet-starter/src/test/java/org/apache/camel/component/kamelet/springboot/KameletBasicTest.java
- components-starter/camel-kamelet-starter/src/test/java/org/apache/camel/component/kamelet/springboot/KameletConsumeOnlyTest.java
- components-starter/camel-kamelet-starter/src/test/java/org/apache/camel/component/kamelet/springboot/KameletConsumerUoWIssueTest.java
Related to https://issues.apache.org/jira/browse/CAMEL-19863
Several tests are failing on the CI
* Disable all the failing tests as long as they are not fixed
> CAMEL-19863: camel-kamelet - Disable failing tests

- tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelUnivocityParsersTest.java
Related to https://issues.apache.org/jira/browse/CAMEL-19864
The integration test of the component `camel-univocity-parsers` is failing on the CI
* Disable the integration test as long as it is not fixed
> CAMEL-19864: camel-univocity-parsers - Disable the IT

- components-starter/camel-http-starter/src/main/java/org/apache/camel/component/http/springboot/HttpComponentTimeoutConverter.java
- components-starter/camel-http-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- components-starter/camel-http-starter/src/test/java/org/apache/camel/component/http/springboot/HttpComponentTimeoutConverterTest.java
Fixes https://issues.apache.org/jira/browse/CAMEL-19851 for 4.1
The timeout can only be configured like any other complex type, indeed, we need to define a dedicated bean in our Spring context and refer to that bean in the configuration of our component which could be simplified by supporting natively timeouts.
* Add new converters to support natively a timeout in milliseconds expressed as long, integer, or string
> CAMEL-19851: camel-http - Allow to configure timeouts natively

- components-starter/camel-fhir-starter/src/test/java/org/apache/camel/component/fhir/FhirUpdateIT.java
Fixes https://issues.apache.org/jira/browse/CAMEL-19867
Some tests of the integration test `FhirUpdateIT` fail on the CI, so they need to be investigated and fixed.
* Backport [the fix](https://github.com/apache/camel-spring-boot/commit/0d365fd48771d0f8a599154c908db179a1f9ebbe) used in the main branch
> Upgrade failing test to FHIR 6.6.1

- components-starter/camel-infinispan-starter/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteAggregationRepositoryIT.java
- components-starter/camel-infinispan-starter/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteAggregationRepositoryOperationsIT.java
Related to https://issues.apache.org/jira/browse/CAMEL-19869
The integration tests `InfinispanRemoteAggregationRepositoryIT` and `InfinispanRemoteAggregationRepositoryOperationsIT` are failing on the CI.
* Disable the integration tests as long as they are not fixed
> CAMEL-19869: camel-infinispan - Disable failing ITs

- components-starter/camel-kamelet-starter/src/test/java/org/apache/camel/component/kamelet/springboot/KameletBasicTest.java
- components-starter/camel-kamelet-starter/src/test/java/org/apache/camel/component/kamelet/springboot/KameletConsumeOnlyTest.java
- components-starter/camel-kamelet-starter/src/test/java/org/apache/camel/component/kamelet/springboot/KameletConsumerUoWIssueTest.java
Add includeMetadata=true to the timer endpoint.
> CAMEL-19863: fix Kamelet tests using timer

- pom.xml
I think we should remove the undertow-version property and use the https://github.com/apache/camel/blob/camel-3.x/parent/pom.xml#L537 version from camel-parent.    It appears like this is already occurring in main (4.x) - undertow.version doesn't exist there https://github.com/apache/camel-spring-boot/blob/main/pom.xml#L116-L132
> Remove undertow-version; use version from camel-parent

- components-starter/camel-xml-jaxb-starter/src/main/java/org/apache/camel/xml/jaxb/springboot/JAXBRuntimeHints.java
- components-starter/camel-xml-jaxb-starter/src/test/java/org/apache/camel/xml/jaxb/springboot/Book.java
fixes the [failing test JAXBRuntimeHintsTest](https://ci-builds.apache.org/job/Camel/job/Camel-Spring-Boot%20Daily%20JDK17/job/main/1458/testReport/junit/org.apache.camel.xml.jaxb.springboot/JAXBRuntimeHintsTest/shouldRegisterHintsForJAXB/)
Since Spring 6.0.13 and the fix for https://github.com/spring-projects/spring-framework/issues/31224, the member category `INVOKE_DECLARED_METHODS` no longer includes public methods so the code needs to be adapted to this behavior change.
* Register also the member category `INVOKE_PUBLIC_METHODS` when `INVOKE_DECLARED_METHODS` is registered
> fix: Adapt JAXBRuntimeHints to the behavior change in Spring 6.0.13

- components-starter/camel-ftp-starter/src/test/java/org/apache/camel/component/file/remote/springboot/ftp/FtpEmbeddedService.java
- components-starter/camel-ftp-starter/src/test/resources/users.properties
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/AddCommentProducerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/AddIssueLinkProducerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/AddIssueProducerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/AddWorkLogProducerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/AttachFileProducerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/DeleteIssueProducerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/FetchCommentsProducerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/FetchIssueProducerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/JiraTestConstants.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/NewCommentsConsumerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/NewIssuesConsumerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/TransitionIssueProducerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/UpdateIssueProducerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/WatchUpdatesConsumerTest.java
- components-starter/camel-jira-starter/src/test/java/org/apache/camel/component/jira/springboot/test/WatcherProducerTest.java
- components-starter/camel-jira-starter/src/test/resources/jiraauth.properties
- tooling/camel-spring-boot-generator-maven-plugin/src/main/java/org/apache/camel/springboot/maven/SpringBootStarterMojo.java
Beginning to review SAST results and implement suggestions - externalize passwords (I still have more starter tests to fix up and will in subsequent commits), set features to DocumentBuilderFactory
> Externalize passwords into properties files, set features to DocumentBuilderFactory

- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/AbstractEncryptedPropertiesIvGeneratorAutoDetectionTest.java
- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/EncryptedPropertiesCustomConfigurationBeansTest.java
- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/EncryptedPropertiesDisabledCustomConfigurationBeansTest.java
- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/EncryptedPropertiesDisabledTest.java
- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/EncryptedPropertiesTest.java
- components-starter/camel-jasypt-starter/src/test/java/org/apache/camel/component/jasypt/springboot/EncryptedPropertiesTestBase.java
- components-starter/camel-jasypt-starter/src/test/resources/test.properties
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/AbstractMongoDbITSupport.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbCredentialsFromUriConnectionIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/meta/integration/MongoDbMetaExtensionIT.java
- components-starter/camel-mongodb-starter/src/test/java/org/apache/camel/component/mongodb/verifier/integration/MongoDbVerifierExtensionIT.java
- components-starter/camel-mongodb-starter/src/test/resources/test.properties
- components-starter/camel-netty-starter/src/test/java/org/apache/camel/component/netty/springboot/NettyComponentConfigurationTest.java
- components-starter/camel-netty-starter/src/test/resources/nettycomponentconfigurationtest.properties
- components-starter/camel-salesforce-starter/src/test/java/org/apache/camel/component/salesforce/springboot/RawPayloadTest.java
- components-starter/camel-salesforce-starter/src/test/resources/rawpayload.properties
Externalize credentials to properties files for SAST tests.    Found a typo in the filename of one of the test classes (EncryptedProperiesTestBase), renamed it.
> Externalize credentials to properties files for SAST tests

- components-starter/camel-infinispan-starter/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteConfigurationIT.java
- components-starter/camel-infinispan-starter/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteTestSupport.java
- components-starter/camel-infinispan-starter/src/test/java/org/apache/camel/component/infinispan/remote/cluster/InfinispanRemoteClusteredTestSupport.java
Adds `infinispan.client_intelligence.basic` system property to set `infinispan.client.hotrod.client_intelligence=BASIC` client property configuration in `camel-infinispan-starter` tests
> [infinispan] Client property configurable in tests

- components-starter/camel-springdoc-starter/pom.xml
- components-starter/camel-springdoc-starter/src/main/java/org/apache/camel/springboot/springdoc/SpringdocAutoConfiguration.java
- pom.xml
Replace springdoc-openapi-ui with springdoc-openapi-starter-webmvc-ui. Update version in the parent pom.
Remove swagger-parser-v3 dependency since it is provided by camel-openapi-java. Fix missing assignment in SpringdocAutoConfiguration.java.
> CAMEL-19793: update dependencies. (#925)

- components-starter/camel-opentelemetry-starter/src/main/docs/opentelemetry.json
- components-starter/camel-opentelemetry-starter/src/main/java/org/apache/camel/opentelemetry/starter/OpenTelemetryConfigurationProperties.java
This adds a "enabled" property to the "camel.opentelemetry" group, to fix IntelliJ `Cannot resolve configuration property 'camel.opentelemetry.enabled'` warnings.
> Add enabled property for OpenTelemetry starter

- core/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/security/CamelSSLAutoConfiguration.java
This make it easier to apply custom configurations based on existing user properties, or, for instance, integrating with other SSL configuration libraries, for instance, https://github.com/Hakky54/sslcontext-kickstart
> Add `@ConditionalOnMissingBeans` on Camel SSL bean auto configuration

- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/ComplexTypesTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiModelApiSecurityRequirementsTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderApiDocsOverrideTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderApiDocsTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderContextPathTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderDayOfWeekTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderEnableVendorExtensionTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderFileResponseModelTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderModelApiSecurityTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderModelBookOrderTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderModelTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderOverrideHostApiDocsTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderPropertyPlaceholderTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiReaderTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/RestOpenApiV2SecuritySchemesTest.java
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/SpringRestOpenApiReaderModelApiSecurityTest.java
It related to
- https://github.com/apache/camel/pull/12316
The RestOpenApiSupport method `getJsonFromOpenAPI` -> `getJsonFromOpenAPIAsString`
> CAMEL-20181: camel-openapi-java - fix compilain errors

- core-starter/camel-k-starter/pom.xml
- core-starter/camel-k-starter/src/main/java/org/apache/camel/spring/boot/k/ApplicationConfiguration.java
- core-starter/camel-k-starter/src/main/java/org/apache/camel/spring/boot/k/ApplicationConstants.java
- core-starter/camel-k-starter/src/main/java/org/apache/camel/spring/boot/k/ApplicationEnvironmentPostProcessor.java
- core-starter/camel-k-starter/src/main/java/org/apache/camel/spring/boot/k/ApplicationRoutesAutoConfiguration.java
- core-starter/camel-k-starter/src/main/java/org/apache/camel/spring/boot/k/ApplicationRoutesCustomizer.java
- core-starter/camel-k-starter/src/main/java/org/apache/camel/spring/boot/k/ApplicationShutdownAutoConfiguration.java
- core-starter/camel-k-starter/src/main/java/org/apache/camel/spring/boot/k/ApplicationShutdownCustomizer.java
- core-starter/camel-k-starter/src/main/resources/META-INF/LICENSE.txt
- core-starter/camel-k-starter/src/main/resources/META-INF/NOTICE.txt
- core-starter/camel-k-starter/src/main/resources/META-INF/spring.factories
- core-starter/camel-k-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- core-starter/camel-k-starter/src/test/java/org/apache/camel/spring/boot/k/ApplicationPropertiesTest.java
- core-starter/camel-k-starter/src/test/java/org/apache/camel/spring/boot/k/ApplicationRoutesTest.java
- core-starter/camel-k-starter/src/test/java/org/apache/camel/spring/boot/k/ApplicationShutdownTest.java
- core-starter/camel-k-starter/src/test/resources/application.properties
- core-starter/camel-k-starter/src/test/resources/camel-k/conf.d/_configmaps/001/application.properties
- core-starter/camel-k-starter/src/test/resources/camel-k/conf.d/_configmaps/001/cm-flat
- core-starter/camel-k-starter/src/test/resources/camel-k/conf.d/_secrets/001/secret-flat
- core-starter/camel-k-starter/src/test/resources/camel-k/conf.properties
- core-starter/camel-k-starter/src/test/resources/camel-k/sources/test-route-001.yaml
- core-starter/camel-k-starter/src/test/resources/camel-k/sources/test-route-002.yaml
- core-starter/camel-k-starter/src/test/resources/logback.xml
- core/camel-spring-boot-xml/src/main/java/org/apache/camel/spring/boot/xml/SpringBootXmlCamelContextConfigurer.java
- core/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/CamelAutoConfiguration.java
Requires https://github.com/apache/camel/pull/13376
> feat: add initial support for camel-k

- components-starter/camel-jasypt-starter/src/main/java/org/apache/camel/component/jasypt/springboot/JasyptEncryptedPropertiesAutoconfiguration.java
- components-starter/camel-jasypt-starter/src/main/java/org/apache/camel/component/jasypt/springboot/JasyptSpringEncryptedPropertiesParser.java
At the moment, the documentation does not work as is, a bean like
```
<bean id="jasypt" class="org.apache.camel.component.jasypt.JasyptPropertiesParser">
<property name="password" value="secret"/>
</bean>
```
has to be defined as primary="true" otherwise two spring beans are loaded in the context for the same class.
Marking beans as conditional solves this issue.
> Make Jasypt beans conditional so that can be overridden

- pom.xml
I think that the only breaking changes are related to Prometheus https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes but it is already updated in Camel
> CAMEL-20779: Upgrade to SB 3.3.0

- components-starter/camel-aws-xray-starter/pom.xml
- components-starter/camel-aws-xray-starter/src/main/docs/aws-xray.json
- components-starter/camel-aws-xray-starter/src/main/java/org/apache/camel/aws/xray/starter/AwsXRayAutoConfiguration.java
- components-starter/camel-aws-xray-starter/src/main/java/org/apache/camel/aws/xray/starter/AwsXRayConfigurationProperties.java
- components-starter/camel-aws-xray-starter/src/main/java/org/apache/camel/aws/xray/starter/CamelAwsXRayTracingStrategy.java
- components-starter/camel-aws-xray-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- components-starter/camel-aws-xray-starter/src/test/java/org/apache/camel/aws/xray/starter/CamelAwsXRayCustomTest.java
- components-starter/camel-aws-xray-starter/src/test/java/org/apache/camel/aws/xray/starter/CamelAwsXRayDisabledTest.java
- components-starter/camel-aws-xray-starter/src/test/java/org/apache/camel/aws/xray/starter/CamelAwsXRayNoopTest.java
- components-starter/camel-aws-xray-starter/src/test/java/org/apache/camel/aws/xray/starter/CamelAwsXRayTest.java
- components-starter/camel-aws-xray-starter/src/test/java/org/apache/camel/aws/xray/starter/CustomAwsXRayTracingStrategy.java
- components-starter/camel-aws-xray-starter/src/test/resources/default.properties
- components-starter/camel-aws-xray-starter/src/test/resources/disabled.properties
- components-starter/camel-aws-xray-starter/src/test/resources/noop.properties
https://issues.apache.org/jira/browse/CAMEL-20868
Enables and configures Camel AWS XRay tracing when _camel-aws-xray-starter_ is added to the classpath. This also adds a _CamelAwsXRayTracingStrategy_ annotation so a custom tracing strategy can be easily used instead of the default _TraceAnnotatedTracingStrategy_.
Thanks !
> CAMEL-20868: camel-aws-xray configure AWS XRay tracing out of the box

- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpConsumer.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/PlatformHttpStreamingTest.java
In order to support support the useStreaming option we could use it to set the `useReaderForPayload` on the `DefaultHttpBinding` class that is responsible for binding between `HttpMessage` and `HttpServletResponse` so that is either uses a reader or an input stream (and `CachedOutputStream`) to read the request body.
> CAMEL-20097: support useStreaming option

- components-starter/camel-jackson-avro-starter/src/test/java/org/apache/camel/component/jackson/avro/springboot/test/JacksonAvroLookupResolverTest.java
- components-starter/camel-jackson-avro-starter/src/test/java/org/apache/camel/component/jackson/avro/springboot/test/JacksonAvroMarshalUnmarshalJsonNodeTest.java
- components-starter/camel-jackson-avro-starter/src/test/java/org/apache/camel/component/jackson/avro/springboot/test/JacksonAvroMarshalUnmarshalPojoListTest.java
- components-starter/camel-jackson-avro-starter/src/test/java/org/apache/camel/component/jackson/avro/springboot/test/JacksonAvroMarshalUnmarshalPojoTest.java
- pom.xml
- tooling/camel-spring-boot-dependencies/pom.xml
Camel is using avro-version 1.12.0 https://github.com/apache/camel/blob/main/parent/pom.xml#L75
Update the version of avro to 1.12.0.     The one API change I found was in avro Schema.Parser, changing setValidate(true) to Parser(NameValidator.STRICT_VALIDATOR).     Ran the tests on camel-avro* and camel-*-avro and it seems okay to me.
> Upgrade avro-version to 1.12.0 to match camel

- components-starter/camel-braintree-starter/pom.xml
- components-starter/camel-jackson-avro-starter/src/test/java/org/apache/camel/component/jackson/avro/springboot/test/JacksonAvroLookupResolverTest.java
- components-starter/camel-jackson-avro-starter/src/test/java/org/apache/camel/component/jackson/avro/springboot/test/JacksonAvroMarshalUnmarshalJsonNodeTest.java
- components-starter/camel-jackson-avro-starter/src/test/java/org/apache/camel/component/jackson/avro/springboot/test/JacksonAvroMarshalUnmarshalPojoListTest.java
- components-starter/camel-jackson-avro-starter/src/test/java/org/apache/camel/component/jackson/avro/springboot/test/JacksonAvroMarshalUnmarshalPojoTest.java
- pom.xml
- tooling/camel-spring-boot-dependencies/pom.xml
Cherry pick back the fix for CAMEL-21243 and the avro version update https://github.com/apache/camel-spring-boot/commit/7160ee1d3d042878dc8261fb43e75409b6afe209 to the camel-spring-boot-4.8.x branch
Ran build locally, saw no issues
> CAMEL-21243 Add dependencyManagement entry for org.osgi:org.osgi.core for camel-braintree-starter

- components-starter/camel-platform-http-starter/pom.xml
- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpAutoConfiguration.java
- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpConsumer.java
- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpEngine.java
The previous implementation was not using full Async code therefore we noticed issues under some circumstances.
The following implementation uses the Async interceptor provided by Spring Boot, right now the stack trace is similar to a plain Spring Boot Async RestController.
> Use SB Async Interceptor

- core/camel-spring-boot-xml/pom.xml
I'm finding a circular dependency in the use of camel-jetty-starter as a test resource in camel-spring-boot-xml - in a clean build camel-jetty-starter is never built by the time that camel-spring-boot-xml tries to build.
I poked around and I think what's required by the test case isn't the camel-jetty-starter but only the camel-jetty component as the only reference is here inside of a camelContext:
https://github.com/apache/camel-spring-boot/blob/main/core/camel-spring-boot-xml/src/test/resources/spring-camel-context.xml#L28
> Use camel-jetty component rather than camel-jetty-starter to prevent circular dependency

- core/camel-spring-boot-xml/pom.xml
I'm finding a circular dependency in the use of camel-jetty-starter as a test resource in camel-spring-boot-xml - in a clean build camel-jetty-starter is never built by the time that camel-spring-boot-xml tries to build.
I poked around and I think what's required by the test case isn't the camel-jetty-starter but only the camel-jetty component as the only reference is here inside of a camelContext: 
https://github.com/apache/camel-spring-boot/blob/main/core/camel-spring-boot-xml/src/test/resources/spring-camel-context.xml#L28
> Use camel-jetty component as a test resource rather than camel-jetty-starter because of circular dependency

- components-starter/camel-observability-services-starter/pom.xml
- components-starter/camel-observability-services-starter/src/main/resources/META-INF/LICENSE.txt
- components-starter/camel-observability-services-starter/src/main/resources/META-INF/NOTICE.txt
- components-starter/camel-observability-services-starter/src/main/resources/config/application.properties
- components-starter/pom.xml
- tooling/camel-spring-boot-bom/pom.xml
- tooling/camel-spring-boot-dependencies/pom.xml
In this PR we're adding the starter for the component.
> feat(components): add observability services starter

- components-starter/camel-observability-services-starter/pom.xml
- components-starter/camel-observability-services-starter/src/main/resources/config/application.properties
Ref https://github.com/apache/camel/pull/16320 - merge this PR once the other is merged in core.
> feat(components): add Opentelemetry into observability-services-starter

- pom.xml
camel/parent.xml has a jolokia-version https://github.com/cunningt/camel-spring-boot/pull/new/jolokiavers
I'd like to remove the jolokia-version specified in camel-spring-boot in favor of the camel version (less properties to maintain).    Ran the camel-jolokia-starter tests and they pass with camel's jolokia-version (2.1.2).
> Remove jolokia-version, use the jolokia-version from camel/parent/pom.xml

- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/CamelRequestHandlerMapping.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpCorsCredentialsTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpOptionsTest.java
- components-starter/camel-platform-http-starter/src/test/resources/application.properties
Enable CORS support when using platform-http.
I'm unsure if this caching [here](https://github.com/rinaldodev/camel-spring-boot/blob/951244227f5531b2ae4301e0a27907e252e51a34/components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/CamelRequestHandlerMapping.java#L86-L90) could be an issue. Do we allow changing CORS configurations after initialization?
```java
if (corsConfiguration == null) {
Map<String, String> corsHeaders = restConfiguration.getCorsHeaders();
corsConfiguration = createCorsConfiguration(corsHeaders != null ? corsHeaders : Collections.emptyMap());
}
return corsConfiguration;
```
> CAMEL-21461: platform-http - add CORS support

- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpAutoConfiguration.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpMultipleExecutorsVirtualThreadsTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpVirtualThreadsTest.java
Fix CAMEL-21536 by explicitly accepting either a ThreadPoolTaskExecutor or a SimpleAsyncTaskExecutor.
> Camel 21536

- pom.xml
it aligns with version in Camel Core https://github.com/apache/camel/blob/5fe84bcb4269061f057b296a6b53ddda8e6d1f72/pom.xml#L128
> chore: Upgrade Maven compiler plugin to 3.13.0

- pom.xml
it aligns with the Spring Boot version used
> chore: Upgrade Wiremock Spring Boot version to 3.4.0

- pom.xml
this property was introduced with this commit
https://github.com/apache/camel-spring-boot/commit/c96b417942338355c162701712de3f61534ce52d#diff-3bd5450df7dcb3ed37c45148874e9ef333df5e52678576df6d6711e036670640
it was used in building tools pom which doesn't exist anymore, or t least is not part of camel-spring-boot repository and is only in camel core one. i do not found a reason fo rwhich camel-spring-boot should override this version
> chore: remove unused Groovy property

- .github/dependabot.yml
usually Maven plugin dependencies are automatically updated in Camel core and in fact we should be able to have different ones in most cases
> chore: provide dependabot configuration to update Maven plugins

- pom.xml
I'm wondering why it is not inheriting the version from Camel core bom. And if there is a good reason, I guess we should add it to the allow list of dependabot to have automatic updates
> Align Jakarta Jaxb 4.0.2 with Camel core

- components-starter/camel-hashicorp-vault-starter/pom.xml
**Jira:** https://issues.apache.org/jira/browse/CAMEL-21581
**Description:** 
Removed the ppc64le-specific Maven profile from the camel-hashicorp-vault-starter POM file to simplify the configuration and avoid hardcoding architecture-specific details.
Updated the camel-test-infra to dynamically retrieve the container image details from the [container.properties] file, ensuring a consistent and maintainable approach.
This change allows the appropriate container image to be selected based on the architecture without requiring separate profiles in the POM
**Test Result:**  
[ppc64le_hashicorp_starter_main_build_13.1image.txt](https://github.com/user-attachments/files/18291961/ppc64le_hashicorp_starter_main_build_13.1image.txt)
[x86_hashicorp_starter_main_build_13.1image.txt](https://github.com …
> [CAMEL-21581]: Remove ppc64le-specific maven profile for hashicorp-vault-starter

- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpConsumer.java
- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpEngine.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpCertificationTest.java
The previous implementation was creating 2 threads per request, the first one, created by spring framework via AsyncExecutionInterceptor, and the second one with `CompletableFuture.runAsync`.
This PR avoids the creation of the 2nd thread, this way, the behavior is like plain Spring Boot `@Async`. And the Apache Camel thread pool can be controlled via 
```
spring.task.execution.pool.max-size=10
spring.task.execution.pool.core-size=10
``` 
While improving this behavior I faced an issue with the return object of the service method, in particular, as you can see from https://github.com/apache/camel-spring-boot/compare/main...Croway:suboptimal-thread-usage?expand=1#diff-7844a79d0aab67af46e8f0538438aa37f3c8b8afb04072724cc78fcf8acb17f5R84 the method still returns CompletableFuture, though I am …
> Platform-http do not spawn useless threads

- components-starter/camel-platform-http-starter/pom.xml
- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/CamelRequestHandlerMapping.java
- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/PlatformHttpMessage.java
- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpBinding.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/PlatformHttpAsyncRequestHandlingTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/PlatformHttpStreamingTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpCamelIntegrationsTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpCertificationTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpCookiesTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpCorsCredentialsTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpCorsTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpEngineTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpHandleWriteErrorTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpJacksonConverterTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpMultipleExecutorsTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpMultipleExecutorsVirtualThreadsTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpOptionsTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpProxyTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpRestDSLTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpSessionTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpSpringSessionTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpTypeConverterTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpValidationTest.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpVirtualThreadsTest.java
- Handle `matchOnUriPrefix`. @davsclaus I feel like the implementation is a bit hacky, to implement matchOnUriPrefix I pretty much followed Spring Boot practices, I do not know if there is a clean way to implement it.
- Handle `application/x-www-form-urlencoded` as Map in the body
> CAMEL-21461: platform-http features

- components-starter/camel-platform-http-starter/src/main/docs/platform-http.json
- components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpBinding.java
- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpEngineTest.java
The behavior is slightly different compared to plain Camel https://github.com/apache/camel/pull/17045
the `attachment.getContent()` in Camel is a String, while, in Camel Spring Boot, a FileInputStream, therefore https://github.com/apache/camel-spring-boot/compare/main...Croway:CAMEL-21701?expand=1#diff-e11e7487d45a9ac2f3cc2803af2694c0d238bc6720d49b1cb9e8f1ea4494a99bR109
> CAMEL-21701: Make single file upload easy to access from message body

- archetypes/camel-archetype-spring-boot/src/main/resources/archetype-resources/src/main/resources/application.properties
- core/camel-spring-boot-xml/src/test/java/org/apache/camel/spring/boot/xml/MixedBootAndXmlConfigurationTest.java
- core/camel-spring-boot/src/test/java/org/apache/camel/spring/boot/CamelAutoConfigurationTest.java
- core/camel-spring-boot/src/test/java/org/apache/camel/spring/boot/CamelAutoConfigurationWithCompatPrefixTest.java
> Replaces deprecated camel.springboot.name property

- components-starter/camel-openapi-java-starter/pom.xml
- components-starter/camel-openapi-java-starter/src/test/java/org/apache/camel/openapi/ComplexTypesTest.java
- tooling/camel-spring-boot-dependencies/pom.xml
Hit an error locally with this test and think JSONAssert would make a lot of sense to help debug future errors (better output, not having to worry about order).
> Use JSONAssert rather than assertEquals for better failure output / order insensitivity

- components-starter/camel-infinispan-starter/pom.xml
Before the BOM import the infinispan-api was in test scope, but withe BOM import the infinispan-api is compile scope
clients that imports this starter fails with CNFE of org.infinispan.api.annotations.indexing.option.VectorSimilarity
You can try to run the [infinispan](https://github.com/apache/camel-spring-boot-examples/tree/main/infinispan) example to see how it fails.
> camel-infinispan-starter: Add org.infinispan:infinispan-api dependency

- components-starter/camel-platform-http-starter/src/test/java/org/apache/camel/component/platform/http/springboot/SpringBootPlatformHttpCertificationTest.java
Having trouble running the streamingWithLargeRequestAndResponseBody - change the location to create files in target and make the URL that is invoked match the name of the test.     The URL was previously configured but unused.
> Change the path of the large file written and make the URL for the large body test match

- catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/others.properties
- catalog/camel-catalog-provider-springboot/src/main/resources/org/apache/camel/springboot/catalog/others/spring-cloud-config.json
- components-starter/camel-spring-cloud-config-starter/pom.xml
- components-starter/camel-spring-cloud-config-starter/src/main/java/org/apache/camel/component/spring/cloud/config/springboot/CamelCloudConfigEnvironmentPostProcessor.java
- components-starter/camel-spring-cloud-config-starter/src/main/java/org/apache/camel/component/spring/cloud/config/springboot/SpringBootCloudConfigPropertiesParser.java
- components-starter/camel-spring-cloud-config-starter/src/main/resources/META-INF/LICENSE.txt
- components-starter/camel-spring-cloud-config-starter/src/main/resources/META-INF/NOTICE.txt
- components-starter/camel-spring-cloud-config-starter/src/main/resources/META-INF/spring.factories
- components-starter/pom.xml
- tooling/camel-spring-boot-bom/pom.xml
- tooling/camel-spring-boot-dependencies/pom.xml
The starter does not add much since spring-cloud-config is already integrated with Spring Boot, but, this PR adds an Early Properties function converter, for example, an application.properties like
```
my.db.pass={{spring-config:myPass}}
```
is resolved at runtime.
The other feature `CamelCloudConfigEnvironmentPostProcessor`, is a translation of custom Apache Camel spring cloud config properties to the Spring Boot ones, this way we'll hook into the SB lifecycle with the expected properties, this is handy in case of prototyping with plain Camel, and then export the project to Camel Spring Boot.
> CAMEL-21801: Add Camel Spring Boot starter

- pom.xml
https://github.com/apache/camel/pull/19395 introduced a spring-boot-version to camel/parent/pom.xml because it is required for jbang in the camel project.     Adding it to camel-parent means it is now available in camel-dependencies, which is the parent for org.apache.camel.springboot:spring-boot (https://github.com/apache/camel-spring-boot/blob/main/pom.xml#L23-L27).
I think we can remove the spring-boot version here to avoid duplication/avoid any conflict of versions.
> Remove spring-boot-version; inherited from camel-dependencies
